#Requires AutoHotkey v2.0.2
#SingleInstance Force

; ════════════════════════════════════════════════════════════════════════════
; FlowWM — flow.ahk
; Ready-to-use AutoHotkey v2 keybindings for FlowWM.
; ════════════════════════════════════════════════════════════════════════════
;
; Generated by:  `flow config init --ahk`
; Written to:    %USERPROFILE%\.config\flow\flow.ahk
;
; This file is yours. Edit it freely — FlowWM never overwrites it once it
; exists. Two things you may want to customise (both at the top of the file):
;
;   1. flowExe  — path to flow.exe. Defaults to "flow" (resolved from PATH).
;                 If FlowWM isn't on your PATH, set the full path, e.g.
;                 "C:\Users\you\flow.exe".
;
;   2. Modifier — every binding is held with ScrollLock below. ScrollLock is
;                 the default because it rarely conflicts with anything, but
;                 many compact/laptop keyboards lack it. To switch, do a
;                 find-and-replace of "ScrollLock" with your key, e.g. "Win",
;                 "CapsLock", or "!^" (Alt+Ctrl). Key list:
;                 https://www.autohotkey.com/docs/v2/KeyList.htm
;
; Run at login:  `flow enable-autostart --ahk` (creates a single shell:startup
;                shortcut that runs `flow.exe start --ahk`; idempotent).
; Full dispatch: run `flow dispatch --help` for every available command.
;
; Layout (hold modifier + key):
;   h j k l  focus left/down/up/right          (+Shift = move window)
;                                             (+Ctrl  = merge into column)
;                                             (+Ctrl+Shift = promote to new column)
;   , .      shrink / expand focused column
;   c        center viewport on focused column
;   t        cycle window float <-> tile
;   q        close focused window
;   p        stop the daemon (then this script exits too)
;   1..9,0   switch to workspace 1..10        (+Shift = send window there)
;
; ════════════════════════════════════════════════════════════════════════════

; --- Config ------------------------------------------------------------------
flowExe := "flow"            ; path to flow.exe (PATH by default)

; --- Flow command helpers ----------------------------------------------------
Flow(cmd) {
    global flowExe
    Run(flowExe ' ' cmd, , 'Hide')
}

FlowDispatch(cmd) {
    global flowExe
    Run(flowExe ' dispatch ' cmd, , 'Hide')
}

; --- Stop the daemon ---------------------------------------------------------
ScrollLock & p::{
    Flow("stop")
    ExitApp
}

; --- Focus / move / merge (h j k l) ------------------------------------------
ScrollLock & h::{
    if GetKeyState("Control") and GetKeyState("Shift")
        FlowDispatch("promote left")
    else if GetKeyState("Shift")
        FlowDispatch("move-window left")
    else if GetKeyState("Control")
        FlowDispatch("merge-column left")
    else
        FlowDispatch("focus left")
}

ScrollLock & l::{
    if GetKeyState("Control") and GetKeyState("Shift")
        FlowDispatch("promote right")
    else if GetKeyState("Shift")
        FlowDispatch("move-window right")
    else if GetKeyState("Control")
        FlowDispatch("merge-column right")
    else
        FlowDispatch("focus right")
}

ScrollLock & j::{
    if GetKeyState("Shift")
        FlowDispatch("move-window down")
    else
        FlowDispatch("focus down")
}

ScrollLock & k::{
    if GetKeyState("Shift")
        FlowDispatch("move-window up")
    else
        FlowDispatch("focus up")
}

; --- Column sizing & window mode ---------------------------------------------
ScrollLock & ,::FlowDispatch("shrink-column")
ScrollLock & .::FlowDispatch("expand-column")

ScrollLock & c::FlowDispatch("center")
ScrollLock & t::FlowDispatch("set-window cycle")   ; float <-> tile

; --- Close -------------------------------------------------------------------
ScrollLock & q::FlowDispatch("close-window")

; --- Workspaces (1..9, 0 = 10) -----------------------------------------------
; Tap: switch to workspace N. Shift+N: send the focused window to workspace N.
WorkspaceAction(n) {
    if GetKeyState("Shift")
        FlowDispatch("move-to-workspace " n)
    else
        FlowDispatch("switch-workspace " n)
}

ScrollLock & 1::WorkspaceAction(1)
ScrollLock & 2::WorkspaceAction(2)
ScrollLock & 3::WorkspaceAction(3)
ScrollLock & 4::WorkspaceAction(4)
ScrollLock & 5::WorkspaceAction(5)
ScrollLock & 6::WorkspaceAction(6)
ScrollLock & 7::WorkspaceAction(7)
ScrollLock & 8::WorkspaceAction(8)
ScrollLock & 9::WorkspaceAction(9)
ScrollLock & 0::WorkspaceAction(10)
